// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// elgrincore
List elgrincore(IntegerMatrix YR, NumericMatrix AmetaR, NumericMatrix EnvironmentR, int nbthreads);
RcppExport SEXP _econetwork_elgrincore(SEXP YRSEXP, SEXP AmetaRSEXP, SEXP EnvironmentRSEXP, SEXP nbthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type YR(YRSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type AmetaR(AmetaRSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type EnvironmentR(EnvironmentRSEXP);
    Rcpp::traits::input_parameter< int >::type nbthreads(nbthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(elgrincore(YR, AmetaR, EnvironmentR, nbthreads));
    return rcpp_result_gen;
END_RCPP
}
